[package]
name = "runtime-types"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
parity-scale-codec = { workspace = true }
runtime-types-macro = { workspace = true }
