[package]
name = "runtime-call"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
parity-scale-codec = { workspace = true }
runtime-call-macro = { workspace = true }
